import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Chatbot',
      items: ['chatbot/create-builder-mdx', 'chatbot/create-meta-account', 'chatbot/create-new-channel'],
    },
    {
      type: 'category',
      label: 'CRM',
      items: [
        {
          type: 'category',
          label: 'Configurações',
          items: ['CRM/config/createAdditionalData']
        },
        {
          type: 'category',
          label: 'Eventos',
          items: ['CRM/event/additionalData']
        }
      ]
    },
    {
      type: 'category',
      label: 'Workspace',
      items: [
        {
          type: 'category',
          label: 'Workspace Digital',
          items: ['workspace/workspaceDigital/workspaceDigital']
        },
        {
          type: 'category',
          label: 'Workspace Ticket',
          items: ['workspace/workspaceTicket/workspaceTicket']
        },
        {
          type: 'category',
          label: 'Workspace Presencial',
          items: ['workspace/workspacePresencial/workspacePresencial']
        }
      ]
    },
    {
      type: 'category',
      label: 'Atendimento',
      items: [
        {
          type: 'category',
          label: 'Atendimento Digital',
          items: [
            {
              type: 'category',
              label: 'Atendimento em tempo real',
              items: ['attendance/digitalAttendance/digitalAttendanceRealtime/digitalAttendanceRealtime/digitalAttendanceRealtime', 'attendance/digitalAttendance/digitalAttendanceRealtime/attendanceRealtimeByDepartment/attendanceRealtimeByDepartment']
            },
            {
              type: 'category',
              label: 'Relatórios',
              items: [
                'attendance/digitalAttendance/report/attendanceReport/attendanceReport',
                'attendance/digitalAttendance/report/attendanceReportByDepartment/attendanceReportByDepartment'
              ]
            },
            {
              type: 'category',
              label: 'Cadastro',
              items: [
                'attendance/digitalAttendance/register/department',
                'attendance/digitalAttendance/register/linkUserToDepartment',
                'attendance/digitalAttendance/register/attendanceGroup',
                'attendance/digitalAttendance/register/speciality',
                'attendance/digitalAttendance/register/subSpeciality',
                'attendance/digitalAttendance/register/area',
                'attendance/digitalAttendance/register/subarea',
                'attendance/digitalAttendance/register/attendanceTime',
                'attendance/digitalAttendance/register/exceptionToOpeningHour',
                'attendance/digitalAttendance/register/breakCategory',
                'attendance/digitalAttendance/register/autoMessage',
                'attendance/digitalAttendance/register/officialFile',
                'attendance/digitalAttendance/register/additionalData'
              ]
            },
            {
              type: 'category',
              label: 'Configurações',
              items: [
                'attendance/digitalAttendance/config/messageOutOfTime',
                'attendance/digitalAttendance/config/configMessageHeader'
              ]
            }
          ]
        },
        {
          type: 'category',
          label: 'Atendimento Tickets',
          items: [
            {
              type: 'category',
              label: 'Relatórios',
              items: [
                'attendance/ticketAttendance/report/ticketReport',
                'attendance/ticketAttendance/report/ticketReportByDepartment']
            },
            {
              type: 'category',
              label: 'Configuração',
              items: [
                'attendance/ticketAttendance/config/configEmailInput',
                'attendance/ticketAttendance/config/configEmailOutput']
            }
          ]
        },
        {
          type: 'category',
          label: 'Atendimento Presencial',
          items: [
            {
              type: 'category',
              label: 'Atendimento',
              items: ['attendance/presentialAttendance/attendance/createAttendance']
            },
            {
              type: 'category',
              label: 'Relatório',
              items: [
                'attendance/presentialAttendance/report/attendanceReport'
              ]
            }
          ]
        }
      ]
    },
    {
      type: 'category',
      label: 'Marketing',
      items: [
        {
          type: 'category',
          label: 'Cadastro',
          items: [
            {
              type: 'category',
              label: 'Template',
              items: ['marketing/register/template']
            },
            {
              type: 'category',
              label: 'Público-alvo',
              items: ['marketing/register/targetAudience']
            },
            {
              type: 'category',
              label: 'Campanha',
              items: [
                'marketing/register/campaign/campaigns',
                'marketing/register/campaign/looseNotification'
              ]
            },
            {
              type: 'category',
              label: 'Metadata',
              items: ['marketing/register/metadata']
            }
          ]
        }
      ]
    },
    {
      type: 'category',
      label: 'Forest',
      items: [
        {
          type: 'category',
          label: 'Pulse',
          items: [
            {
              type: 'category',
              label: 'Aplicativos',
              items: ['forest/pulse/app/analytics/analytics']
            }
          ]
        },
        {
          type: 'category',
          label: 'Arquivo',
          items: [
            {
              type: 'category',
              label: 'Cadastro',
              items: ['forest/file/register/files']
            }
          ]
        },
        {
          type: 'category',
          label: 'Chave de API',
          items: [
            {
              type: 'category',
              label: 'Cadastro',
              items: ['forest/apiKey/register/apiKey']
            }
          ]
        }
      ]
    },
    {
      type: 'category',
      label: 'Configuração',
      items: [
        {
          type: 'category',
          label: 'Configuração',
          items: [
            {
              type: 'category',
              label: 'Webhook',
              items: ['config/config/webhook/webhook']
            }
          ]
        },
        {
          type: 'category',
          label: 'Segurança',
          items: [
            {
              type: 'category',
              label: 'Acesso',
              items: ['config/security/acessProfile/acessProfile']
            }
          ]
        }
      ]
    }
  ],
};

export default sidebars;
